apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-prod
  namespace: argocd
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/Itsfoss0/devops-withk8s-config
    targetRevision: main
    path: overlays/prod
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
